[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"


[project]
name = "lib_dzne_igblastn"
version = "0.2.4"
description = "Libary for using igblastn. "
readme = "README.rst"
authors = [{ name = "Johannes", email = "johannes-programming@mailfence.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []
dependencies = [
    'lib_dzne_tsv>=0.1.4',
    'lib-dzne-filedata>=0.4.4',
]
requires-python = ">=3.11"

[project.urls]
source = "https://github.com/johannes-programming/lib-dzne-igblastn"

